# Fichier de configuration pour le script d'optimisation

[model]
# Nom du modèle à utiliser depuis le Hub Hugging Face
name = "distilbert-base-uncased"

[dataset]
# Nom du dataset à utiliser depuis le Hub Hugging Face
name = "imdb"
# Nombre d'échantillons pour l'entraînement. Mettre -1 pour utiliser le dataset complet.
num_samples_train = 1000
# Nombre d'échantillons pour l'évaluation. Mettre -1 pour utiliser le dataset complet.
num_samples_eval = 500

[optimization]
# Nombre d'essais (trials) à exécuter par Optuna
n_trials = 10
# Nom de l'étude Optuna (utilisé pour la base de données)
study_name = "huggingface_optimization"
